name: Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Dockerhub    
        env:
          DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
      - name: Build Docker image
        run: docker build -t hallbregg/tor-proxy:latest
      - name: Push Docker image
        run: docker push ${{secrets.DOCKERHUB_USER}}/tor-proxy
